/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EFCrud.Client;
using EFCrud.Api;
// uncomment below to import models
//using EFCrud.Model;

namespace EFCrud.Test.Api
{
    /// <summary>
    ///  Class for testing AuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AuthApiTests : IDisposable
    {
        private AuthApi instance;

        public AuthApiTests()
        {
            instance = new AuthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AuthApi
            //Assert.IsType<AuthApi>(instance);
        }

        /// <summary>
        /// Test ApiAuthLoginPost
        /// </summary>
        [Fact]
        public void ApiAuthLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Userdto? userdto = null;
            //var response = instance.ApiAuthLoginPost(userdto);
            //Assert.IsType<User>(response);
        }

        /// <summary>
        /// Test ApiAuthRegisterPost
        /// </summary>
        [Fact]
        public void ApiAuthRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? role = null;
            //Userdto? userdto = null;
            //var response = instance.ApiAuthRegisterPost(role, userdto);
            //Assert.IsType<User>(response);
        }
    }
}
