/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EFCrud.Client;
using EFCrud.Api;
// uncomment below to import models
//using EFCrud.Model;

namespace EFCrud.Test.Api
{
    /// <summary>
    ///  Class for testing EmployeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmployeesApiTests : IDisposable
    {
        private EmployeesApi instance;

        public EmployeesApiTests()
        {
            instance = new EmployeesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmployeesApi
            //Assert.IsType<EmployeesApi>(instance);
        }

        /// <summary>
        /// Test ApiEmployeesGet
        /// </summary>
        [Fact]
        public void ApiEmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? name = null;
            //UserRoles? role = null;
            //var response = instance.ApiEmployeesGet(name, role);
            //Assert.IsType<List<Employee>>(response);
        }

        /// <summary>
        /// Test ApiEmployeesIdDelete
        /// </summary>
        [Fact]
        public void ApiEmployeesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiEmployeesIdDelete(id);
        }

        /// <summary>
        /// Test ApiEmployeesIdGet
        /// </summary>
        [Fact]
        public void ApiEmployeesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.ApiEmployeesIdGet(id);
            //Assert.IsType<Employee>(response);
        }

        /// <summary>
        /// Test ApiEmployeesIdPut
        /// </summary>
        [Fact]
        public void ApiEmployeesIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //Employee? employee = null;
            //instance.ApiEmployeesIdPut(id, employee);
        }

        /// <summary>
        /// Test ApiEmployeesPost
        /// </summary>
        [Fact]
        public void ApiEmployeesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Employee? employee = null;
            //var response = instance.ApiEmployeesPost(employee);
            //Assert.IsType<Employee>(response);
        }
    }
}
