/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EFCrud.Client;
using EFCrud.Api;

namespace EFCrud.Test.Api
{
    /// <summary>
    ///  Class for testing FeaturesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FeaturesApiTests : IDisposable
    {
        private FeaturesApi instance;

        public FeaturesApiTests()
        {
            instance = new FeaturesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeaturesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FeaturesApi
            //Assert.IsType<FeaturesApi>(instance);
        }

        /// <summary>
        /// Test ApiFeaturesIdDelete
        /// </summary>
        [Fact]
        public void ApiFeaturesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //bool? isdeleted = null;
            //bool? isactive = null;
            //instance.ApiFeaturesIdDelete(id, isdeleted, isactive);
        }

        /// <summary>
        /// Test ApiFeaturesIdPut
        /// </summary>
        [Fact]
        public void ApiFeaturesIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //bool? isman = null;
            //bool? issup = null;
            //instance.ApiFeaturesIdPut(id, isman, issup);
        }
    }
}
