/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EFCrud.Client;
using EFCrud.Api;
// uncomment below to import models
//using EFCrud.Model;

namespace EFCrud.Test.Api
{
    /// <summary>
    ///  Class for testing RolesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RolesApiTests : IDisposable
    {
        private RolesApi instance;

        public RolesApiTests()
        {
            instance = new RolesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RolesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RolesApi
            //Assert.IsType<RolesApi>(instance);
        }

        /// <summary>
        /// Test ApiRolesAddEmployeeRolePost
        /// </summary>
        [Fact]
        public void ApiRolesAddEmployeeRolePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? name = null;
            //UserRoles? role = null;
            //instance.ApiRolesAddEmployeeRolePost(name, role);
        }

        /// <summary>
        /// Test ApiRolesAddRolesPost
        /// </summary>
        [Fact]
        public void ApiRolesAddRolesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Roles? roles = null;
            //instance.ApiRolesAddRolesPost(roles);
        }

        /// <summary>
        /// Test ApiRolesDeleteEmpRoleDelete
        /// </summary>
        [Fact]
        public void ApiRolesDeleteEmpRoleDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? name = null;
            //UserRoles? role = null;
            //instance.ApiRolesDeleteEmpRoleDelete(name, role);
        }

        /// <summary>
        /// Test ApiRolesShowEmployeeRolesGet
        /// </summary>
        [Fact]
        public void ApiRolesShowEmployeeRolesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiRolesShowEmployeeRolesGet();
        }

        /// <summary>
        /// Test ApiRolesShowRolesGet
        /// </summary>
        [Fact]
        public void ApiRolesShowRolesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiRolesShowRolesGet();
        }
    }
}
