/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using EFCrud.Client;
using EFCrud.Model;

namespace EFCrud.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>User</returns>
        User ApiAuthLoginPost(Userdto? userdto = default(Userdto?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> ApiAuthLoginPostWithHttpInfo(Userdto? userdto = default(Userdto?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>User</returns>
        User ApiAuthRegisterPost(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> ApiAuthRegisterPostWithHttpInfo(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> ApiAuthLoginPostAsync(Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> ApiAuthLoginPostWithHttpInfoAsync(Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> ApiAuthRegisterPostAsync(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> ApiAuthRegisterPostWithHttpInfoAsync(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApi : IAuthApiSync, IAuthApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthApi : IAuthApi
    {
        private EFCrud.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi(string basePath)
        {
            this.Configuration = EFCrud.Client.Configuration.MergeConfigurations(
                EFCrud.Client.GlobalConfiguration.Instance,
                new EFCrud.Client.Configuration { BasePath = basePath }
            );
            this.Client = new EFCrud.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EFCrud.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = EFCrud.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthApi(EFCrud.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = EFCrud.Client.Configuration.MergeConfigurations(
                EFCrud.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new EFCrud.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EFCrud.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = EFCrud.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AuthApi(EFCrud.Client.ISynchronousClient client, EFCrud.Client.IAsynchronousClient asyncClient, EFCrud.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = EFCrud.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public EFCrud.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public EFCrud.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public EFCrud.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public EFCrud.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>User</returns>
        public User ApiAuthLoginPost(Userdto? userdto = default(Userdto?), int operationIndex = 0)
        {
            EFCrud.Client.ApiResponse<User> localVarResponse = ApiAuthLoginPostWithHttpInfo(userdto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of User</returns>
        public EFCrud.Client.ApiResponse<User> ApiAuthLoginPostWithHttpInfo(Userdto? userdto = default(Userdto?), int operationIndex = 0)
        {
            EFCrud.Client.RequestOptions localVarRequestOptions = new EFCrud.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EFCrud.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EFCrud.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = userdto;

            localVarRequestOptions.Operation = "AuthApi.ApiAuthLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<User>("/api/Auth/login", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> ApiAuthLoginPostAsync(Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            EFCrud.Client.ApiResponse<User> localVarResponse = await ApiAuthLoginPostWithHttpInfoAsync(userdto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<EFCrud.Client.ApiResponse<User>> ApiAuthLoginPostWithHttpInfoAsync(Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            EFCrud.Client.RequestOptions localVarRequestOptions = new EFCrud.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EFCrud.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EFCrud.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = userdto;

            localVarRequestOptions.Operation = "AuthApi.ApiAuthLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<User>("/api/Auth/login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>User</returns>
        public User ApiAuthRegisterPost(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0)
        {
            EFCrud.Client.ApiResponse<User> localVarResponse = ApiAuthRegisterPostWithHttpInfo(role, userdto);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of User</returns>
        public EFCrud.Client.ApiResponse<User> ApiAuthRegisterPostWithHttpInfo(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0)
        {
            EFCrud.Client.RequestOptions localVarRequestOptions = new EFCrud.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EFCrud.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EFCrud.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (role != null)
            {
                localVarRequestOptions.QueryParameters.Add(EFCrud.Client.ClientUtils.ParameterToMultiMap("", "role", role));
            }
            localVarRequestOptions.Data = userdto;

            localVarRequestOptions.Operation = "AuthApi.ApiAuthRegisterPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<User>("/api/Auth/register", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthRegisterPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> ApiAuthRegisterPostAsync(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            EFCrud.Client.ApiResponse<User> localVarResponse = await ApiAuthRegisterPostWithHttpInfoAsync(role, userdto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="EFCrud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="role"> (optional)</param>
        /// <param name="userdto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<EFCrud.Client.ApiResponse<User>> ApiAuthRegisterPostWithHttpInfoAsync(string? role = default(string?), Userdto? userdto = default(Userdto?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            EFCrud.Client.RequestOptions localVarRequestOptions = new EFCrud.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EFCrud.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EFCrud.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (role != null)
            {
                localVarRequestOptions.QueryParameters.Add(EFCrud.Client.ClientUtils.ParameterToMultiMap("", "role", role));
            }
            localVarRequestOptions.Data = userdto;

            localVarRequestOptions.Operation = "AuthApi.ApiAuthRegisterPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<User>("/api/Auth/register", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAuthRegisterPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
