/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EFCrud.Model;
using EFCrud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EFCrud.Test.Model
{
    /// <summary>
    ///  Class for testing Roles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RolesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Roles
        //private Roles instance;

        public RolesTests()
        {
            // TODO uncomment below to create an instance of Roles
            //instance = new Roles();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Roles
        /// </summary>
        [Fact]
        public void RolesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Roles
            //Assert.IsType<Roles>(instance);
        }

        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Fact]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }

        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [Fact]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
    }
}
