/*
 * EmployeeEFCrud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EFCrud.Model;
using EFCrud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EFCrud.Test.Model
{
    /// <summary>
    ///  Class for testing Userdto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserdtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Userdto
        //private Userdto instance;

        public UserdtoTests()
        {
            // TODO uncomment below to create an instance of Userdto
            //instance = new Userdto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Userdto
        /// </summary>
        [Fact]
        public void UserdtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" Userdto
            //Assert.IsType<Userdto>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
