name: .NET

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Update Version in .csproj
        run: |
          version=$(echo "${{ steps.get_latest_release.outputs.RELEASE_TAG }}")
          sed -i "s/<Version>.*<\/Version>/<Version>$version<\/Version>/" src/EFCrud/EFCrud.csproj
          git config --local user.email "dprakash2101@gmail.com"
          git config --local user.name "dprakash2101"
          git add .
          git commit -m "Update version in .csproj" || true
          git push

      - name: Build Package
        run: dotnet pack -c Release --output github-package/ 
      - name: Commit and Push Package
        run: |
          git config --local user.email "dprakash2101@gmail.com"
          git config --local user.name "dprakash2101"
          git add github-package/*.nupkg
          git commit -m "Add NuGet package" || true
          git push

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish to NuGet
        run: dotnet nuget push ./github-package/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
