name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build Package
      run: dotnet pack -c Release

    - name: Create Directory
      run: mkdir -p github-package

    - name: Move Package to Directory
      run: mv *.nupkg github-package/

    - name: Commit and Push Package
      run: |

        git add github-package/*.nupkg
        git commit -m "Add NuGet package" || true
        git push
